import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { UserProvider } from "./context/user.provider";
import { TokenProvider } from "./context/token.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <UserProvider>
          <TokenProvider>
            <MantineProvider>{children}</MantineProvider>
          </TokenProvider>
        </UserProvider>
      </body>
    </html>
  );
}
